# Generated by Django 4.1.7 on 2023-03-14 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 14, 4, 20, 14, 831853)),
        ),
    ]
