# Generated by Django 4.1.7 on 2023-03-14 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 3, 14, 4, 29, 20, 654330), null=True),
        ),
    ]
